
FROM node:18 AS builder

WORKDIR /usr/src/frontend


COPY frontend/package.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /usr/src/frontend/build /usr/share/nginx/html

EXPOSE 80
